### ISSUE TITLE
it will not run to the bat file this code worked for me inside the bat fille 

### ISSUE THREAD

**Issue by PS4Testing** [andy-man/ps4-wee-tools#32]
@echo off
setlocal
set "python_executable=python"  REM Or specify the full path to the Python interpreter
%python_executable% "%~dp0\ps4-wee-tools.py" %*
pause

**Comment by andy-man** [comment]
Don't forget enable "**Add Python to PATH**" during installation

_Simple solution: Re-install python_

**For those who want to understand more:**

It is better to check your **PATH** variable in "Environment Variables" in Windows 
(Control Panel > System > Advanced system settings > System Variables)

_For python 3.8 it should be like this:_
C:\Program Files\Python38\Scripts\
C:\Program Files\Python38\

Use **python** instead of **py** _(if you have not installed **py**)_
You can check is py installed in your system by typing: **where py** (in command prompt)
